---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp enviar-contato.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
